"""create table toys

Revision ID: 439e118cbb67
Revises: f91ba7806d15
Create Date: 2020-02-15 15:00:44.812429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '439e118cbb67'
down_revision = 'f91ba7806d15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.Text(), nullable=True),
    sa.Column('puppy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['puppy_id'], ['puppies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toys')
    # ### end Alembic commands ###
